### PR TITLE
Manifestv2, bookworm fixes

### PR DESCRIPTION
**Pull request by Salamandar**

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by Salamandar** [comment]
!bookwormtestme

**Comment by Salamandar** [comment]
!testme

**Comment by Salamandar** [comment]
!bookwormtestme

**Comment by ericgaspar** [comment]
!bookwormtestme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
> Revert removal of --usage=low --footprint=low for fpm 

I think we don't need those anymore, (if we add `extra_php-fpm.conf`)

**Comment by Salamandar** [comment]
> > Revert removal of --usage=low --footprint=low for fpm
> 
> I think we don't need those anymore, (if we add `extra_php-fpm.conf`)

You mean an empty one ?

**Comment by Salamandar** [comment]
!bookwormtestme

**Pull request merged**
